version: '3'
services:
  managementui:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    container_name: rabbit-management
    hostname: rabbit-management
  broker:
    image: rabbitmq:3
    container_name: rabbit-broker
    hostname: rabbit-broker
  server:
    image: python:3.8.1
    container_name: rabbit-server
    hostname: rabbit-server
    depends_on:
      - broker
    volumes:
      - ./server:/src
    command: ./src/startup.sh
  client:
    image: python:3.8.1
    container_name: rabbit-client
    hostname: rabbit-client
    depends_on:
      - server
    volumes:
      - ./client:/src
    command: ./src/startup.sh
