version: "3.8"
services:
  broker:
    image: rabbitmq:3.12.4-management-alpine
    container_name: rabbitmq-broker
    hostname: rabbitmq-broker
    ports:
      - 15672:15672

  server:
    image: python:3.11.5-alpine
    container_name: rabbitmq-server
    hostname: rabbitmq-server
    command: ./usr/src/scripts/startup.sh
    depends_on:
      - broker
    volumes:
      - ./server:/usr/src

  client:
    image: python:3.11.5-alpine
    container_name: rabbitmq-client
    hostname: rabbitmq-client
    command: ./usr/src/scripts/startup.sh
    depends_on:
      - server
    volumes:
      - ./client:/usr/src
