version: '3'
services:
  broker:
    image: rabbitmq:3.8.2-management
    ports:
      - 15672:15672
    container_name: rabbit-broker
    hostname: rabbit-broker
  producer:
    image: python:3.8.1
    container_name: rabbit-producer
    hostname: rabbit-producer
    depends_on:
      - broker
    volumes:
      - ./producer:/src
    command: ./src/startup.sh
  consumer_one:
    image: python:3.8.1
    container_name: rabbit-consumer-one
    hostname: rabbit-consumer-one
    depends_on:
      - producer
    volumes:
      - ./consumer_one:/src
    command: ./src/startup.sh
  consumer_two:
    image: python:3.8.1
    container_name: rabbit-consumer-two
    hostname: rabbit-consumer-two
    depends_on:
      - producer
    volumes:
      - ./consumer_two:/src
    command: ./src/startup.sh
