version: "3.8"
services:
  broker:
    image: rabbitmq:3.12.4-alpine
    container_name: rabbitmq-broker
    hostname: rabbitmq-broker

  producer:
    image: python:3.11.5-alpine
    container_name: rabbitmq-producer
    hostname: rabbitmq-producer
    command: ./usr/src/scripts/startup.sh
    volumes:
      - ./producer:/usr/src

  consumer:
    image: python:3.11.5-alpine
    container_name: rabbitmq-consumer
    hostname: rabbitmq-consumer
    command: ./usr/src/scripts/startup.sh
    volumes:
      - ./consumer:/usr/src
