version: "3.8"
services:
  broker:
    image: rabbitmq:3.12.4-alpine
    container_name: rabbitmq-broker
    hostname: rabbitmq-broker

  exchange:
    image: python:3.11.5-alpine
    container_name: rabbitmq-exchange
    hostname: rabbitmq-exchange
    command: ./usr/src/scripts/startup.sh
    depends_on:
      - broker
    volumes:
      - ./exchange:/usr/src

  consumer_a:
    image: python:3.11.5-alpine
    container_name: rabbitmq-consumer-a
    hostname: rabbitmq-consumer-a
    command: ./usr/src/scripts/startup.sh
    depends_on:
      - exchange
    volumes:
      - ./consumer:/usr/src

  consumer_b:
    image: python:3.11.5-alpine
    container_name: rabbitmq-consumer-b
    hostname: rabbitmq-consumer-b
    command: ./usr/src/scripts/startup.sh
    depends_on:
      - exchange
    volumes:
      - ./consumer:/usr/src
