asyncapi: 2.6.0
info:
  title: Routing
  version: '1.0.0'
  description: |
    Implementation of routing inspired by this [tutorial](https://www.rabbitmq.com/tutorials/tutorial-four-python.html).

defaultContentType: application/json

servers:
  development:
    url: rabbitmq-broker:5671
    protocol: amqp
    description: RabbitMQ broker development server.
    security:
      - user-password: []
      - certificates: []

channels:
  logs:
    publish:
      description: |
        Exchange can send messages to following routing keys:
        - error
        - info
        - warning
      bindings:
        amqp:
          is: routingKey
          exchange:
            name: logs
            type: direct
            vhost: /
      message:
        contentEncoding: utf-8
        $ref: '#/components/messages/logMsg'
    subscribe:
      description: |
        Exchange can receive messages to following routing keys:
        - error
        - info
        - warning
      bindings:
        amqp:
          is: routingKey
          exchange:
            name: logs
            type: direct
            vhost: /
      message:
        contentEncoding: utf-8
        $ref: '#/components/messages/logMsg'

components:
  messages:
    logMsg:
      name: logMsg
      title: logMsg
      contentType: application/json
      payload:
        type: object
        properties:
          message:
            type: string

  securitySchemes:
    user-password:
      type: userPassword
    certificates:
      type: X509
